services:
  # Backend API Service
  - type: web
    name: customwall-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: DB_NAME
        value: memorywall
      - key: EMAIL_USER
        value: ""
      - key: EMAIL_PASS
        value: ""

  # Frontend React App
  - type: web
    name: customwall-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://customwall-backend.onrender.com

# Comment out database for free deployment - use external free database
# databases:
#   - name: customwall-db
#     databaseName: memorywall
#     user: customwall_user 